And/Or/Gcd/Lcm convolution
BRUTEUdesc/AlmanaqueBrute pull request #134
Opened 2024-06-22 20:43 UTC by eemoreira

codigos e readme de And/Or/Gcd/Lcm convolution

2024-06-24 13:10 UTC, joaomarcosth9 requested changes
Muito bom os códigos com variável maiúscula, virei fã.

Alguns pontos deixei sugestão no código, e tem outros:

- Colocar os nomes dos arquivos .cpp com underline, `and_convolution.cpp`, etc. E as pastas coloca os nomes maiúsculos nas operações, AND-Convolution, GCD-convolution, etc.
- Usar o Mint? Ou só trocar aquelas adições com módulo lá pela adição com if pra ser mais rápido.

2024-06-24 13:10 UTC, joaomarcosth9 commented on Codigos/Matemática/Convolução/And-Convolution/README.md
> +Obs: /\ representa o bitwise and.
```suggestion
# [AND Convolution](and-convolution.cpp)

Calcula o vetor $C$ a partir de $A$ e $B$ onde $C[i] = \sum_{\substack{(j \land k) = i}} A[j] \cdot B[k]$ em $\mathcal{O}(N \cdot \log N)$.

Obs: $\land$ representa o bitwise and.
```

2024-06-24 13:10 UTC, joaomarcosth9 commented on Codigos/Matemática/Convolução/And-Convolution/and-convolution.cpp
> +    int n = int(max(A.size(), B.size()));
```suggestion
    int n = (int)max(A.size(), B.size());
```

2024-06-24 13:10 UTC, joaomarcosth9 commented on Codigos/Matemática/Convolução/Gcd-Convolution/README.md
> +Calcula o vetor $C$ a partir de $A$ e $B$ onde $C[i] = \sum_{\substack{gcd(j, k) = i}} A[j] \cdot B[k]$ em $\mathcal{O}(N \cdot log N)$.
```suggestion
# [GCD Convolution](gcd-convolution.cpp)

Calcula o vetor $C$ a partir de $A$ e $B$ onde $C[i] = \sum_{\substack{gcd(j, k) = i}} A[j] \cdot B[k]$ em $\mathcal{O}(N \cdot \log N)$.
```

2024-06-24 13:10 UTC, joaomarcosth9 commented on Codigos/Matemática/Convolução/Lcm-Convolution/README.md
> +Calcula o vetor $C$ a partir de $A$ e $B$ $C[i] = \sum_{\substack{lcm(j, k) = i}} A[j] \cdot B[k]$ em $\mathcal{O}(N \cdot log N)$.
```suggestion
# [LCM Convolution](lcm-convolution.cpp)

Calcula o vetor $C$ a partir de $A$ e $B$ $C[i] = \sum_{\substack{lcm(j, k) = i}} A[j] \cdot B[k]$ em $\mathcal{O}(N \cdot \log N)$.
```

2024-06-24 13:10 UTC, joaomarcosth9 commented on Codigos/Matemática/Convolução/Or-Convolution/README.md
> +Calcula o vetor $C$ a partir de $A$ e $B$ tal que $C[i] = \sum_{\substack{(j \| k) = i}} A[j] \cdot B[k]$ em $\mathcal{O}(N \cdot logN)$
```suggestion
# [OR Convolution](or-convolution.cpp)

Calcula o vetor $C$ a partir de $A$ e $B$ tal que $C[i] = \sum_{\substack{(j \| k) = i}} A[j] \cdot B[k]$ em $\mathcal{O}(N \cdot \log N)$
```

2024-06-24 13:10 UTC, joaomarcosth9 commented on Codigos/Matemática/Convolução/Or-Convolution/or-convolution.cpp
> +    int n = int(max(A.size(), B.size()));
```suggestion
template <int MOD>
vector<int> or_convolution(vector<int> A, vector<int> B) {
    int n = (int)max(A.size(), B.size());
```

2024-06-24 13:10 UTC, joaomarcosth9 commented on Codigos/Matemática/Convolução/Gcd-Convolution/gcd-convolution.cpp
> +    int N = int(max(A.size(), B.size()));
```suggestion
template <int MOD>
vector<int> gcd_convolution(vector<int> A, vector<int> B) {
    int N = (int)max(A.size(), B.size());
```

2024-06-24 20:30 UTC, EMachad0 approved these changes

2024-06-24 20:30 UTC, EMachad0 commented on Codigos/Matemática/Convolução/And-Convolution/and_convolution.cpp
> +    }
May look nicer
```suggestion
    while (two < n) two <<= 1, N++;
```

2024-06-24 20:30 UTC, EMachad0 commented on Codigos/Matemática/Convolução/Or-Convolution/or_convolution.cpp
> +    }
same here
```suggestion
    while (two < n) two <<= 1, N++;
```

2024-06-25 00:34 UTC, joaomarcosth9 requested changes
os nomes das pastas não tão maiúsculos aqui pra mim ainda 🤔 (o OR, AND, GCD e LCM)

2024-06-26 13:28 UTC, joaomarcosth9 approved these changes
Top

2024-06-26 14:06 UTC, merged