add kosaraju
BRUTEUdesc/AlmanaqueBrute pull request #139
Opened 2024-06-28 18:51 UTC by EMachad0

2024-07-02 13:23 UTC, joaomarcosth9 requested changes

2024-07-02 13:23 UTC, joaomarcosth9 commented on Codigos/Grafos/Kosaraju/kosaraju.cpp
> +                    sete.insert(ii(ru, rv));
```suggestion
        set<pair<int, int>> st;
        for (int u = 0; u < n; u++) {
            int ru = root[u];
            for (int v : adj[u]) {
                int rv = root[v];
                if (ru == rv) continue;
                if (!st.count(ii(ru, rv))) {
                    gc[ru].emplace_back(rv);
                    st.insert(ii(ru, rv));
```

sete é mt feio, parece o número 7

2024-07-02 20:08 UTC, EMachad0 commented on Codigos/Grafos/Kosaraju/kosaraju.cpp
> +                    sete.insert(ii(ru, rv));
sete é superior, mas voces não estão preparados pra essa conversa

2024-07-02 23:50 UTC, joaomarcosth9 requested changes

2024-07-02 23:50 UTC, joaomarcosth9 commented on Codigos/Grafos/Kosaraju/kosaraju.cpp
> +                    sete.insert(ii(ru, rv));
```suggestion
                if (!st.count(ii(ru, rv))) {
                    gc[ru].emplace_back(rv);
                    st.insert(ii(ru, rv));
```

2024-07-06 22:19 UTC, joaomarcosth9 approved these changes

2024-07-07 14:05 UTC, merged